version: 2
project_name: apisnip

before:
  hooks:
    # We don't need this for Rust
    # - go mod tidy

# This is using GoReleaser's Rust support
builds:
  - id: apisnip
    binary: apisnip
    builder: rust
    # Specify the build strategy - use plain cargo instead of zigbuild
    command: build
    # For Rust we use targets instead of goos/goarch
    targets:
      # Linux targets
      - x86_64-unknown-linux-gnu
      - aarch64-unknown-linux-gnu
      - i686-unknown-linux-gnu
      # Windows targets using GNU toolchain for cross-compilation
      - x86_64-pc-windows-gnu
      - i686-pc-windows-gnu
      # macOS targets
      - x86_64-apple-darwin
      # - aarch64-apple-darwin
    flags:
      - --release
    # env:
    #   # Required environment variables for macOS cross-compilation
    #   - MACOSX_DEPLOYMENT_TARGET=10.7
    #   - CC=o64-clang
    #   - CXX=o64-clang++
    hooks:
      pre:
        - rustup target add {{ .Target }}
        # Full osxcross setup and env vars for macOS targets
        - sh -c '
          case "{{ .Target }}" in 
            *apple-darwin*) 
              echo "Setting up osxcross and env for {{ .Target }}...";
              if [ ! -d /tmp/osxcross ]; then 
                echo "Cloning osxcross..."; 
                git clone https://github.com/tpoechtrager/osxcross.git /tmp/osxcross; 
                cd /tmp/osxcross; 
                echo "Getting dependencies (might need sudo)..."; 
                ./tools/get_dependencies.sh || echo "Dependency script failed, continuing..."; 
                echo "Downloading macOS SDK..."; 
                wget -nc -q https://github.com/joseluisq/macosx-sdks/releases/download/12.3/MacOSX12.3.sdk.tar.xz -O ./tarballs/MacOSX12.3.sdk.tar.xz || echo "SDK download failed, continuing..."; 
                echo "Building osxcross (this may take a while)..."; 
                UNATTENDED=1 ./build.sh || echo "osxcross build failed, continuing..."; 
              else 
                echo "osxcross directory already exists."; 
              fi; 
              echo "Adding osxcross to PATH and setting CC/CXX..."; 
              export PATH="/tmp/osxcross/target/bin:$PATH"; 
              export MACOSX_DEPLOYMENT_TARGET=10.7
              export CC=o64-clang
              export CXX=o64-clang++
              echo "Environment set for macOS build.";
              ;;
            *) 
              echo "Not a macOS target, skipping osxcross setup and env vars.";
              ;;
          esac
          '
      post:
        - upx "{{ .Path }}" || true  # Add back the UPX compression but don't fail if it doesn't work

archives:
  - format_overrides:
      - goos: windows
        formats: [ 'zip' ]
    name_template: >-
      {{ .ProjectName }}-
      {{- .Version }}-
      {{- if eq .Os "darwin" }}macos
      {{- else }}{{ .Os }}{{ end }}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

nfpms:
  - file_name_template: >-
      {{ .ProjectName }}-
      {{- .Version }}-
      {{- .Os }}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    homepage: https://github.com/Tuurlijk/apisnip
    description: "A terminal user interface tool for trimming OpenAPI specifications down to size"
    maintainer: Tuurlijk
    license: MIT
    vendor: Tuurlijk
    formats:
      - deb
      - rpm
      - apk
      - archlinux
      - termux
      - flatpak
      - snap
      - nix
      - ebuild
    contents:
      - src: resources/icons/linux/apisnip.svg
        dst: /usr/share/icons/hicolor/scalable/apps/apisnip.svg
      - src: resources/icons/linux/16x16/apisnip.png
        dst: /usr/share/icons/hicolor/16x16/apps/apisnip.png
      - src: resources/icons/linux/32x32/apisnip.png
        dst: /usr/share/icons/hicolor/32x32/apps/apisnip.png
      - src: resources/icons/linux/48x48/apisnip.png
        dst: /usr/share/icons/hicolor/48x48/apps/apisnip.png
      - src: resources/icons/linux/64x64/apisnip.png
        dst: /usr/share/icons/hicolor/64x64/apps/apisnip.png
      - src: resources/icons/linux/128x128/apisnip.png
        dst: /usr/share/icons/hicolor/128x128/apps/apisnip.png
      - src: resources/icons/linux/256x256/apisnip.png
        dst: /usr/share/icons/hicolor/256x256/apps/apisnip.png

universal_binaries:
  - replace: true

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: Tuurlijk
    name: apisnip
  prerelease: auto
  draft: false
  mode: replace
  footer: |
    ## How to install
    
    ### macOS
    ```bash
    brew install tuurlijk/tap/apisnip
    ```
    
    ### Linux
    Download the .deb, .rpm, or .tar.gz file for your platform from the [releases page](https://github.com/Tuurlijk/apisnip/releases/latest)
    
    ### Windows
    Download the Windows .zip file from the [releases page](https://github.com/Tuurlijk/apisnip/releases/latest)
    
    ### Binary
    ```bash
    curl -sfL https://raw.githubusercontent.com/Tuurlijk/apisnip/main/install.sh | sh
    ```