version: 2
project_name: apisnip

# Build-only configuration
# All other sections (archives, nfpms, release, etc.) removed
# Kept for the build jobs

builds:
  - id: linux-win
    binary: apisnip
    builder: rust
    command: build
    targets:
      # Linux targets
      - x86_64-unknown-linux-gnu
      - aarch64-unknown-linux-gnu
      - i686-unknown-linux-gnu
      # Windows targets using GNU toolchain for cross-compilation
      - x86_64-pc-windows-gnu
      - i686-pc-windows-gnu
    flags:
      - --release
    hooks:
      pre: []
      post:
        - upx "{{ .Path }}" || true

  - id: macos
    binary: apisnip
    builder: rust
    command: build
    targets:
      # macOS targets
      - x86_64-apple-darwin
      - aarch64-apple-darwin
    flags:
      - --release
    hooks:
      pre:
        - rustup target add {{ .Target }}
      # No post hook for macOS (UPX disabled)