version: 2
project_name: apisnip

builds:
  - id: linux-win
    binary: apisnip
    builder: rust
    command: build
    targets:
      # Linux targets
      - x86_64-unknown-linux-gnu
      - aarch64-unknown-linux-gnu
      - i686-unknown-linux-gnu
      # Windows targets using GNU toolchain for cross-compilation
      - x86_64-pc-windows-gnu
      - i686-pc-windows-gnu
    flags:
      - --release
    hooks:
      pre: []
      post:
        - upx "{{ .Path }}" || true

  - id: macos
    binary: apisnip
    builder: rust
    command: build
    targets:
      # macOS targets
      - x86_64-apple-darwin
      - aarch64-apple-darwin
    flags:
      - --release
    hooks:
      pre:
        - rustup target add {{ .Target }}
      # No post hook for macOS (UPX disabled)

archives:
  - format_overrides:
      - goos: windows
        formats: [ 'zip' ]
    name_template: >-
      {{ .ProjectName }}-
      {{- .Version }}-
      {{- if eq .Os "darwin" }}macos
      {{- else }}{{ .Os }}{{ end }}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

nfpms:
  - file_name_template: >-
      {{ .ProjectName }}-
      {{- .Version }}-\n      {{- .Os }}-\n      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    homepage: https://github.com/Tuurlijk/apisnip
    description: "A terminal user interface tool for trimming OpenAPI specifications down to size"
    maintainer: Tuurlijk
    license: MIT
    vendor: Tuurlijk
    formats:
      - deb
      - rpm
      - apk
      - archlinux
      - termux
      - flatpak
      - snap
      - nix
      - ebuild
    contents:
      - src: resources/icons/linux/apisnip.svg
        dst: /usr/share/icons/hicolor/scalable/apps/apisnip.svg
      - src: resources/icons/linux/16x16/apisnip.png
        dst: /usr/share/icons/hicolor/16x16/apps/apisnip.png
      - src: resources/icons/linux/32x32/apisnip.png
        dst: /usr/share/icons/hicolor/32x32/apps/apisnip.png
      - src: resources/icons/linux/48x48/apisnip.png
        dst: /usr/share/icons/hicolor/48x48/apps/apisnip.png
      - src: resources/icons/linux/64x64/apisnip.png
        dst: /usr/share/icons/hicolor/64x64/apps/apisnip.png
      - src: resources/icons/linux/128x128/apisnip.png
        dst: /usr/share/icons/hicolor/128x128/apps/apisnip.png
      - src: resources/icons/linux/256x256/apisnip.png
        dst: /usr/share/icons/hicolor/256x256/apps/apisnip.png

universal_binaries:
  - replace: true

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: Tuurlijk
    name: apisnip
  prerelease: auto
  draft: false
  mode: replace
  footer: |
    ## How to install
    
    ### macOS
    ```bash
    brew install tuurlijk/tap/apisnip
    ```
    
    ### Linux
    Download the .deb, .rpm, or .tar.gz file for your platform from the [releases page](https://github.com/Tuurlijk/apisnip/releases/latest)
    
    ### Windows
    Download the Windows .zip file from the [releases page](https://github.com/Tuurlijk/apisnip/releases/latest)
    
    ### Binary
    ```bash
    curl -sfL https://raw.githubusercontent.com/Tuurlijk/apisnip/main/install.sh | sh
    ```