openapi: 3.0.1
info:
  title: GitLab API
  version: v4
servers:
- url: //gitlab.com/
tags:
- name: award_emoji
  description: Operations about award_emoji
- name: badges
  description: Operations about badges
- name: groups
  description: Operations about groups
- name: runners
  description: Operations about runners
- name: group_avatar
  description: Operations about group_avatars
- name: invitations
  description: Operations about invitations
- name: members
  description: Operations about members
- name: personal_access_tokens
  description: Operations about personal_access_tokens
- name: group_access_tokens
  description: Operations about group_access_tokens
- name: wikis
  description: Operations about wikis
- name: alert_management
  description: Operations about alert_managements
- name: branches
  description: Operations about branches
- name: secure_files
  description: Operations about secure_files
- name: commits
  description: Operations about commits
- name: pages
  description: Operations about pages
- name: pages_domains
  description: Operations about pages_domains
- name: project_avatar
  description: Operations about project_avatars
- name: projects_job_token_scope
  description: Operations about projects_job_token_scopes
- name: project_snippets
  description: Operations about project_snippets
- name: protected_tags
  description: Operations about protected_tags
- name: remote_mirrors
  description: Operations about remote_mirrors
- name: project_access_tokens
  description: Operations about project_access_tokens
- name: tags
  description: Operations about tags
- name: batched_background_migrations
  description: Operations about batched_background_migrations
- name: admin
  description: Operations about admins
- name: migrations
  description: Operations about migrations
- name: broadcast_messages
  description: Operations about broadcast_messages
- name: applications
  description: Operations about applications
- name: avatar
  description: Operations about avatars
- name: bulk_imports
  description: Operations about bulk_imports
- name: job
  description: Operations about jobs
- name: jobs
  description: Operations about jobs
- name: events
  description: Operations about events
- name: users
  description: Operations about users
- name: keys
  description: Operations about keys
- name: markdown
  description: Operations about markdowns
- name: namespaces
  description: Operations about namespaces
- name: organizations
  description: Operations about organizations
- name: project_repository_storage_moves
  description: Operations about project_repository_storage_moves
- name: snippets
  description: Operations about snippets
- name: snippet_repository_storage_moves
  description: Operations about snippet_repository_storage_moves
- name: hooks
  description: Operations about hooks
- name: usage_data
  description: Operations about usage_data
- name: metrics
  description: Operations about metrics
- name: user
  description: Operations about users
- name: user_counts
  description: Operations about user_counts
- name: application
  description: Operations about applications
- name: import
  description: Operations about imports
- name: slack
  description: Operations about slacks
- name: topics
  description: Operations about topics
- name: web_commits
  description: Operations about web_commits
- name: access_requests
  description: Operations related to access requests
- name: ci_lint
  description: Operations related to linting a CI config file
- name: ci_resource_groups
  description: Operations to manage job concurrency with resource groups
- name: ci_variables
  description: Operations related to CI/CD variables
- name: cluster_agents
  description: Operations related to the GitLab agent for Kubernetes
- name: clusters
  description: Operations related to clusters
- name: composer_packages
  description: Operations related to Composer packages
- name: conan_packages
  description: Operations related to Conan packages
- name: container_registry
  description: Operations related to container registry
- name: container_registry_event
  description: Operations related to container registry events
- name: debian_distribution
  description: Operations related to Debian Linux distributions
- name: debian_packages
  description: Operations related to Debian Linux packages
- name: dependency_proxy
  description: Operations to manage dependency proxy for a groups
- name: deploy_keys
  description: Operations related to deploy keys
- name: deploy_tokens
  description: Operations related to deploy tokens
- name: deployments
  description: Operations related to deployments
- name: dora_metrics
  description: Operations related to DevOps Research and Assessment (DORA) key metrics
- name: environments
  description: Operations related to environments
- name: error_tracking_client_keys
  description: Operations related to error tracking client keys
- name: error_tracking_project_settings
  description: Operations related to error tracking project settings
- name: feature_flags_user_lists
  description: Operations related to accessing GitLab feature flag user lists
- name: feature_flags
  description: Operations related to feature flags
- name: features
  description: Operations related to managing Flipper-based feature flags
- name: freeze_periods
  description: Operations related to deploy freeze periods
- name: generic_packages
  description: Operations related to Generic packages
- name: geo
  description: Operations related to Geo
- name: geo_nodes
  description: Operations related Geo Nodes
- name: go_proxy
  description: Operations related to Go Proxy
- name: group_export
  description: Operations related to exporting groups
- name: group_import
  description: Operations related to importing groups
- name: group_packages
  description: Operations related to group packages
- name: helm_packages
  description: Operations related to Helm packages
- name: integrations
  description: Operations related to integrations
- name: issue_links
  description: Operations related to issue links
- name: jira_connect_subscriptions
  description: Operations related to JiraConnect subscriptions
- name: maven_packages
  description: Operations related to Maven packages
- name: merge_requests
  description: Operations related to merge requests
- name: metadata
  description: Operations related to metadata of the GitLab instance
- name: ml_model_registry
  description: Operations related to Model registry
- name: npm_packages
  description: Operations related to NPM packages
- name: nuget_packages
  description: Operations related to Nuget packages
- name: package_files
  description: Operations about package files
- name: plan_limits
  description: Operations related to plan limits
- name: project_export
  description: Operations related to exporting projects
- name: project_hooks
  description: Operations related to project hooks
- name: project_import
  description: Operations related to importing projects
- name: project_import_bitbucket
  description: Operations related to importing BitBucket projects
- name: project_import_github
  description: Operations related to importing GitHub projects
- name: project_packages
  description: Operations related to project packages
- name: projects
  description: Operations related to projects
- name: protected environments
  description: Operations related to protected environments
- name: pypi_packages
  description: Operations related to PyPI packages
- name: release_links
  description: Operations related to release assets (links)
- name: releases
  description: Operations related to releases
- name: resource_milestone_events
  description: Operations about resource milestone events
- name: rpm_packages
  description: Operations related to RPM packages
- name: rubygem_packages
  description: Operations related to RubyGems
- name: suggestions
  description: Operations related to suggestions
- name: system_hooks
  description: Operations related to system hooks
- name: terraform_state
  description: Operations related to Terraform state files
- name: terraform_registry
  description: Operations related to the Terraform module registry
- name: unleash_api
  description: Operations related to Unleash API
paths: {}
components:
  schemas: {}
  securitySchemes:
    access_token_header:
      type: apiKey
      name: PRIVATE-TOKEN
      in: header
    access_token_query:
      type: apiKey
      name: private_token
      in: query
