[package]
name = "apisnip"
description = "Trim an API surface down to size ✂️"
version = "0.1.0"
edition = "2024"

[dependencies]
openapi = "0.1"
clap = { version = "4.5.32", features = ["derive"] }
crossterm = { version = "0.28.1", features = ["event-stream"] }
ratatui = "0.29.0"
progenitor-client = { git = "https://github.com/oxidecomputer/progenitor" }
reqwest = { version = "0.12", features = ["json", "stream"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.140"
serde_yaml = "0.9"
tokio = { version = "1.0.0", features = ["rt", "rt-multi-thread", "macros"] }
chrono = "0.4"
color-eyre = "0.6.3"
tokio-stream = "0.1.17"
dirs = "6.0.0"
config = "0.15.11"
tui-textarea = { path = "../tui-textarea" }
chrono-tz = "0.8"
lazy_static = "1.4.2"
log = "0.4.20"
env_logger = "0.11.1"
once_cell = "1.21.1"
unicode-width = "0.1.14"
itertools = "0.13.0"
fakeit = "1.3.0"

[build-dependencies]
regex = "1.10.3"
