name: Release Packages
on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  # Release with GoReleaser
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        
      # Install Rust
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      
      # Install cross-compilation targets
      - name: Install targets
        run: |
          rustup target add x86_64-unknown-linux-gnu
          rustup target add aarch64-unknown-linux-gnu
          rustup target add i686-unknown-linux-gnu
          rustup target add x86_64-apple-darwin
          rustup target add aarch64-apple-darwin
          rustup target add x86_64-pc-windows-msvc
          rustup target add i686-pc-windows-msvc
      
      # Install dependencies for building packages
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-multilib g++-multilib
          sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
          sudo apt-get install -y libc6-dev-i386
          # For Windows cross-compilation
          sudo apt-get install -y gcc-mingw-w64
          # For packaging
          sudo apt-get install -y ruby ruby-dev rpm build-essential
          sudo gem install fpm
      
      # Install UPX for binary compression
      - name: Install UPX
        run: sudo apt-get install -y upx
      
      # Cache dependencies
      - uses: Swatinem/rust-cache@v2
      
      # Run GoReleaser
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 