name: Release Packages
on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  # Single job using goreleaser-cross Docker image
  goreleaser:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
          targets: x86_64-unknown-linux-gnu,aarch64-unknown-linux-gnu,i686-unknown-linux-gnu,x86_64-pc-windows-gnu,i686-pc-windows-gnu,x86_64-apple-darwin,aarch64-apple-darwin

      # Cache Rust dependencies
      - uses: Swatinem/rust-cache@v2

      # Install UPX for binary compression
      - name: Install UPX
        run: sudo apt-get update && sudo apt-get install -y upx

      # Run GoReleaser to build and publish in a container
      - name: Run GoReleaser
        uses: docker://ghcr.io/goreleaser/goreleaser-cross:v1.24
        with:
          entrypoint: /bin/sh
          args: -c "apt-get update && apt-get install -y curl && curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y && . $HOME/.cargo/env && rustup target add x86_64-unknown-linux-gnu aarch64-unknown-linux-gnu i686-unknown-linux-gnu x86_64-pc-windows-gnu i686-pc-windows-gnu x86_64-apple-darwin aarch64-apple-darwin && goreleaser release --clean"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 